"""empty message

Revision ID: 0d3b8406751d
Revises: None
Create Date: 2016-11-12 22:54:12.434463

"""

# revision identifiers, used by Alembic.
revision = '0d3b8406751d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_data_type', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('custom_data_type', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'custom_data_type', 'user', ['user_id'], ['id'])
    op.add_column('model', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('model', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'model', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.drop_column('model', 'user_id')
    op.drop_column('model', 'created_at')
    op.drop_constraint(None, 'custom_data_type', type_='foreignkey')
    op.drop_column('custom_data_type', 'user_id')
    op.drop_column('custom_data_type', 'created_at')
    ### end Alembic commands ###
