"""empty message

Revision ID: 15de4b9903fe
Revises: None
Create Date: 2016-12-20 20:39:53.951593

"""

# revision identifiers, used by Alembic.
revision = '15de4b9903fe'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(length=32), nullable=True),
    sa.Column('parent_node', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'model', 'fields')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'model', sa.Column('fields', postgresql.ARRAY(HSTORE(text_type=Text())), autoincrement=False, nullable=True))
    op.drop_table('field')
    # ### end Alembic commands ###
