"""empty message

Revision ID: 6e76d083b27b
Revises: None
Create Date: 2016-12-09 21:23:32.870344

"""

# revision identifiers, used by Alembic.
revision = '6e76d083b27b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field', sa.Column('parent_node', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field', 'parent_node')
    ### end Alembic commands ###
