"""empty message

Revision ID: 8d9fc056f026
Revises: None
Create Date: 2016-12-05 20:12:33.659770

"""

# revision identifiers, used by Alembic.
revision = '8d9fc056f026'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field', sa.Column('data_type', sa.String(length=32), nullable=True))
    op.drop_constraint(u'field_ibfk_2', 'field', type_='foreignkey')
    op.drop_column('field', 'data_type_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field', sa.Column('data_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'field_ibfk_2', 'field', 'native_data_type', ['data_type_id'], ['id'])
    op.drop_column('field', 'data_type')
    ### end Alembic commands ###
