"""empty message

Revision ID: 9ea1f39d84e3
Revises: bea330a41346
Create Date: 2016-11-22 21:08:41.894102

"""

# revision identifiers, used by Alembic.
revision = '9ea1f39d84e3'
down_revision = 'bea330a41346'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authenticated')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authenticated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    ### end Alembic commands ###
