"""empty message

Revision ID: adb5c3c082b7
Revises: 9ea1f39d84e3
Create Date: 2016-11-27 14:22:12.313747

"""

# revision identifiers, used by Alembic.
revision = 'adb5c3c082b7'
down_revision = '9ea1f39d84e3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('native_data_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('data_type_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_type_id'], ['native_data_type.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'custom_data_type', sa.Column('custom_data_type_name', sa.String(length=50), nullable=True))
    op.add_column(u'custom_data_type', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'custom_data_type', 'native_data_type', ['id'], ['id'])
    op.drop_column(u'custom_data_type', 'name')
    op.add_column(u'model', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'model', 'updated_at')
    op.add_column(u'custom_data_type', sa.Column('name', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'custom_data_type', type_='foreignkey')
    op.drop_column(u'custom_data_type', 'updated_at')
    op.drop_column(u'custom_data_type', 'custom_data_type_name')
    op.drop_table('field')
    op.drop_table('native_data_type')
    ### end Alembic commands ###
