"""empty message

Revision ID: f0d33bef5c08
Revises: adb5c3c082b7
Create Date: 2016-11-27 16:24:12.077951

"""

# revision identifiers, used by Alembic.
revision = 'f0d33bef5c08'
down_revision = 'adb5c3c082b7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_data_type', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_column('custom_data_type', 'custom_data_type_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_data_type', sa.Column('custom_data_type_name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('custom_data_type', 'name')
    ### end Alembic commands ###
